#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d 6 7 8 9 10
bspc monitor HDMI-0 -d 1 2 3 4 5

bspc config border_width         5
bspc config window_gap          10

# colors
bspc config normal_border_color "#c9c9c9"  
bspc config active_border_color "#c9c9c9"  
bspc config focused_border_color "#258a38" 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a gimp desktop='^2' state=tiled follow=on
bspc rule -a librewolf desktop='^6'
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a feh state=floating
bspc rule -a virt-manager desktop='^3' state=floating
bspc rule -a sneedacity desktop='^8' state=tiled sticky=on
bspc rule -a /usr/bin/puddletag desktop=^5 state=fullscreen follow=off

# Set dual monitor orientation
xrandr --output DP-1 --left-of HDMI-0

# Run script to launch Polybar
$HOME/.config/polybar/launch.sh

# Run Picom
picom &

# Initialize X resource database
xrdb ~/.Xresources

# Set background
feh --bg-tile $HOME/Pictures/wallpapers/bluebonnets_tile1.png
